DELETE FROM core_global_id;
ALTER TABLE core_global_id AUTO_INCREMENT = 1;
UPDATE core_note SET global_id_fk = NULL;
UPDATE core_blog SET global_id_fk = NULL;
UPDATE core_attachment SET global_id_fk = NULL;
UPDATE user_entity SET global_id_fk = NULL;
UPDATE core_tag SET global_id_fk = NULL;
INSERT INTO core_global_id (GLOBAL_IDENTIFIER) SELECT CONCAT('/', (select sett.`value` from configuration_setting sett where sett.`key` = 'kenmei.unique.client.identifer'), '/note/', note.id) FROM core_note note;
INSERT INTO core_global_id (GLOBAL_IDENTIFIER) SELECT CONCAT('/', (select sett.`value` from configuration_setting sett where sett.`key` = 'kenmei.unique.client.identifer'), '/blog/', blog.id) FROM core_blog blog;
INSERT INTO core_global_id (GLOBAL_IDENTIFIER) SELECT CONCAT('/', (select sett.`value` from configuration_setting sett where sett.`key` = 'kenmei.unique.client.identifer'), '/attachment/', attachment.id) FROM core_attachment attachment;
INSERT INTO core_global_id (GLOBAL_IDENTIFIER) SELECT CONCAT('/', (select sett.`value` from configuration_setting sett where sett.`key` = 'kenmei.unique.client.identifer'), '/tag/', tag.id) FROM core_tag tag;
INSERT INTO core_global_id (GLOBAL_IDENTIFIER) SELECT CONCAT('/', (select sett.`value` from configuration_setting sett where sett.`key` = 'kenmei.unique.client.identifer'), '/user/', user_.id) FROM user_user user_;
INSERT INTO core_global_id (GLOBAL_IDENTIFIER) SELECT CONCAT('/', (select sett.`value` from configuration_setting sett where sett.`key` = 'kenmei.unique.client.identifer'), '/group/', group_.id) FROM user_group group_;
UPDATE core_note,core_global_id       SET core_note.global_id_fk = core_global_id.ID       WHERE core_note.global_id_fk IS NULL AND core_global_id.GLOBAL_IDENTIFIER = CONCAT( '/', (select sett.`value` from configuration_setting sett where sett.`key` = 'kenmei.unique.client.identifer'), '/note/', core_note.ID );
UPDATE core_blog,core_global_id       SET core_blog.global_id_fk = core_global_id.ID       WHERE core_blog.global_id_fk IS NULL AND core_global_id.GLOBAL_IDENTIFIER = CONCAT( '/', (select sett.`value` from configuration_setting sett where sett.`key` = 'kenmei.unique.client.identifer'), '/blog/', core_blog.ID );
UPDATE core_attachment,core_global_id SET core_attachment.global_id_fk = core_global_id.ID WHERE core_attachment.global_id_fk IS NULL AND core_global_id.GLOBAL_IDENTIFIER = CONCAT( '/', (select sett.`value` from configuration_setting sett where sett.`key` = 'kenmei.unique.client.identifer'), '/attachment/', core_attachment.ID );
UPDATE core_tag,core_global_id        SET core_tag.global_id_fk = core_global_id.ID        WHERE core_tag.global_id_fk IS NULL AND core_global_id.GLOBAL_IDENTIFIER = CONCAT( '/', (select sett.`value` from configuration_setting sett where sett.`key` = 'kenmei.unique.client.identifer'), '/tag/', core_tag.ID );
UPDATE user_entity,core_global_id     SET user_entity.global_id_fk = core_global_id.ID     WHERE user_entity.global_id_fk IS NULL AND core_global_id.GLOBAL_IDENTIFIER = CONCAT( '/', (select sett.`value` from configuration_setting sett where sett.`key` = 'kenmei.unique.client.identifer'), '/group/', user_entity.ID );
UPDATE user_entity,core_global_id     SET user_entity.global_id_fk = core_global_id.ID     WHERE user_entity.global_id_fk IS NULL AND core_global_id.GLOBAL_IDENTIFIER = CONCAT( '/', (select sett.`value` from configuration_setting sett where sett.`key` = 'kenmei.unique.client.identifer'), '/user/', user_entity.ID );