
package com.communote.plugins.webservice.helloworld;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 * @author Communote GmbH - <a href="http://www.communote.com/">http://www.communote.com/</a>
 */
@WebService(name = "Hello_PortType", targetNamespace = "http://www.examples.com/wsdl/HelloService.wsdl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloPortType {


    /**
     * 
     * @param firstName
     * @return
     *     returns String
     */
    @WebMethod(action = "sayHello")
    @WebResult(name = "greeting", partName = "greeting")
    public String sayHello(
        @WebParam(name = "firstName", partName = "firstName")
        String firstName);

}
